### ISSUE TITLE
Notifications not showing when app is in background or foreground

### ISSUE THREAD

**Issue by bruxalldev** [pushy-me/pushy-flutter#11]
Hi we have a flutter app that works fine on a number of android devices but this particular model doesn't want to show notifications on the home screen or when the app is in foreground mode.

Tablet Model

Lenovo Tab E8
Android 7 Nougat

and in our app

 pushy_flutter:
    dependency: "direct main"
    description:
      name: pushy_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.9"

**Comment by pushy-me** [comment]
Hi @bruxalldev,
Thanks for reaching out.

This issue may have to do with the push payload you're sending. Can you please send the `data` object you're sending to the [Send Notifications API](https://pushy.me/docs/api/send-notifications)?

**Comment by pushy-me** [comment]
Closing due to lack of response, feel free to comment to reopen.
