### ISSUE TITLE
build with pushy_flutter package error in flutter

### ISSUE THREAD

**Issue by Yazan99sh** [pushy-me/pushy-flutter#12]
I trying to install pushy package but when i installed and rebuild project 
showing to me this error

-----------------------------------------
### Environment
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.43.1)
[√] Connected device (4 available)

• No issues found!
----------------------------------------
### Consol
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':pushy_flutter'.
> Could not resolve all artifacts for configuration ':pushy_flutter:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.2.1/tracker-26.2.1.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.2.1/shared-26.2.1.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.2.1/crash-26.2.1.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.2.1/lint-gradle-api-26.2.1.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.2.1/gradle-api-3.2.1.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.2.1/databinding-compiler-common-3.2.1.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.2.1/manifest-merger-26.2.1.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.2.1/sdk-common-26.2.1.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.2.1/builder-test-api-3.2.1.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.2.1/ddmlib-26.2.1.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.2.1/sdklib-26.2.1.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.2.1/layoutlib-api-26.2.1.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.2.1/dvlib-26.2.1.jar
   > Could not find repository.jar (com.android.tools:repository:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.2.1/repository-26.2.1.jar
   > Could not find common.jar (com.android.tools:common:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.2.1/common-26.2.1.jar
   > Could not find jetifier-processor.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-alpha10).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-alpha10/jetifier-processor-1.0.0-alpha10.jar
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.5.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.5.0/bundletool-0.5.0.jar
   > Could not find jetifier-core.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-alpha10/jetifier-core-1.0.0-alpha10.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.2.1/builder-model-3.2.1.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.2.1/protos-26.2.1.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.2.1/apkzlib-3.2.1.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.2.1/apksig-3.2.1.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.2.1/annotations-26.2.1.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.2.1/databinding-common-3.2.1.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.2.1/baseLibrary-3.2.1.jar
> Could not get unknown property 'android' for project ':pushy_flutter' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_local_notifications...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-1.4.4+4\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Exception: The plugin flutter_local_notifications could not be built due to the issue above.

**Comment by pushy-me** [comment]
Hi @Yazan99sh,
We'd be glad to assist.

According to a [similar report on StackOverflow](https://stackoverflow.com/questions/61860915/could-not-resolve-all-artifacts-for-configuration-flutter-local-notifications), the solution is to upgrade Gradle to the latest version by following the instructions here:
https://gradle.org/install/#with-the-gradle-wrapper

Since this issue is not caused by the Pushy Flutter SDK itself, it will be closed.
