### ISSUE TITLE
Device not waking up when receiving a notification

### ISSUE THREAD

**Issue by calvinmuller** [pushy-me/pushy-flutter#13]
```
pushy_flutter: ^1.0.12
```
When the device is locked and we send a notification - the device screen does not come on nor does it show a notification bar?

Do you have any ideas how we can awake the device and show a notification that can be clicked?

Thanks

**Comment by pushy-me** [comment]
Hi @calvinmuller,
Thanks for reaching out. We'd be glad to assist with your issue.

Please consult this article for a solution:
[How can I send notifications to Android devices in Doze / power saving mode?
](https://support.pushy.me/hc/en-us/articles/360043423332)

Please let me know if there's anything else I can help with.
