### ISSUE TITLE
No notification if the app is terminated or killed.

### ISSUE THREAD

**Issue by engrjabi** [pushy-me/pushy-flutter#17]
Hi, I'm also encountering the issue on the notification not being shown if the app is closed. does the flutter sdk already handle the sending of notifications even if the app is closed? I checked the source code and it seems it is using the flutter isolate library. It seems flutter isolate is also killed if the app is already killed

**Comment by pushy-me** [comment]
Hi @engrjabi,
We'd be glad to assist with your inquiry.

The Pushy Flutter SDK will attempt to start a background isolate process if your app is killed, if the notification was able to be received by the SDK (the connection with our servers is active).

If you could please provide the following information about the device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by engrjabi** [comment]
Hi,

1) Device manufacturer - Xiaomi
2) Device model name - Redmi Note 8 Pro
3) Android OS version - Andriod 9

Is this issue on flutter isolate relevant to this issue? - https://github.com/rmawatson/flutter_isolate/issues/21

**Comment by pushy-me** [comment]
Hi @engrjabi,
Thanks for providing the requested information.

Some Chinese Android manufacturers (Xiaomi included) make use of [custom power-saving restrictions](https://support.pushy.me/hc/en-us/articles/360043864791-Why-do-some-Chinese-devices-fail-to-receive-notifications-in-the-background-) that inhibit sending push notifications to your users while your app is in the background, swiped away from recent apps, or after a device restart. 

If the affected devices are not within mainland China, we recommend implementing our [FCM high priority fallback delivery](https://pushy.me/docs/resources/fcm-fallback-delivery). This is proven to work around several of these manufacturers' custom power saving mechanisms (Xiaomi, OnePlus, and more), by having Pushy deliver your notifications through MQTT and Firebase Cloud Messaging's high-priority channel simultaneously, while only waking up your app once. 

When the notification comes through FCM, the Pushy Flutter SDK will be able to start a Flutter background isolate and call your notification listener.

Please let us know if you have any further questions.

**Comment by engrjabi** [comment]
I see, I will try this, thanks!

**Comment by ShaysFrame** [comment]
What about devices in China then ;-; I'm facing the same issue and it seems like nothing is working... Google fcm can't be used in China.... Help someone! 🥲

**Comment by pushy** [comment]
Hi @ShaysFrame,
We'd be glad to assist.

Implementing one of the below solutions will make it possible for your users to receive notifications in real time on Chinese manufacturer devices within mainland China:

1) Exempting your app from Android's power saving optimizations will make it possible to receive notifications:

**a)** If your app will be distributed through Google Play, consider asking your users to disable battery optimizations for your app by displaying an in-app dialog with instructions and firing the [`ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS`](https://developer.android.com/reference/android/provider/Settings#action_ignore_battery_optimization_settings) activity (completely safe and will not get your app suspended from Google Play):

![Image](https://github.com/user-attachments/assets/1f0f358b-af03-4ba7-8532-777aa8cedc70)

The code for displaying this dialog is as follows:

```
if (Platform.isAndroid) {
  // Check if app is ignoring battery optimizations
  var whitelisted = await Pushy.isIgnoringBatteryOptimizations();

  // Show dialog if not whitelisted
  if (!whitelisted) {
    showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text("Disable battery optimizations"),
            titleTextStyle: TextStyle(
                fontWeight: FontWeight.bold,
                color: Colors.black,
                fontSize: 20),
            actionsOverflowButtonSpacing: 20,
            actions: [
              ElevatedButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: Text("Cancel")),
              ElevatedButton(
                  onPressed: () {
                    // Launch the battery optimizations settings screen
                    Pushy.launchBatteryOptimizationsActivity();

                    // Close dialog
                    Navigator.pop(context);
                  },
                  child: Text("OK"))
            ],
            content: Text(
                "If you'd like to receive notifications in the background, please click OK and select \"All apps\" -> MyApp -> Don't optimize."),
          );
      });
    }
}
```

**Note:** To whitelist your app from battery optimizations manually, you can long press your app launcher icon -> App Info -> Battery -> Set to "Unrestricted".

**b)** If you're not distributing your app through Google Play, you can make it possible for your users to exempt your app from battery optimizations without leaving your app:

![Image](https://github.com/user-attachments/assets/d94651ed-06ee-436b-b30f-fbae464f307a)

First, declare the following permission in your `AndroidManifest.xml`:

```
<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
```

Next, call the following native Java code from one of your activities to display an in-app dialog to the user which will allow them to whitelist your app from battery optimizations without leaving your app:

```
// Get instance of Power Manager
PowerManager powerManager = (PowerManager) getSystemService(Context.POWER_SERVICE);

// Android M (6) and up only
// Check if the user has not already whitelisted your app from battery optimizations
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && !powerManager.isIgnoringBatteryOptimizations(getPackageName())) {
    // Display an in-app dialog which will allow the user to exempt your app without leaving it
    startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, Uri.parse("package:"+getPackageName())));
}
```

**Note:** Please do not use the above solution if you are distributing your app through Google Play, as it will most likely lead to app suspension.

2) Consider implementing our [foreground service functionality](https://support.pushy.me/hc/en-us/articles/8961466967437). The Pushy Android SDK will create a foreground service that the Android OS will never terminate, which will ensure that Chinese power saving restrictions will not terminate your app. In turn, a fully customizable notification will be displayed in the notification bar. It is possible to instruct your users to easily hide the ongoing notification. More details are available [here](https://support.pushy.me/hc/en-us/articles/8961466967437).

Please let us know if there's anything else we can help with.
