### ISSUE TITLE
NotificationListener doesn't work when work with Firebase Auth together

### ISSUE THREAD

**Issue by anthonycmeow** [pushy-me/pushy-flutter#18]
Hello Team,

I noticed backgroundNotificationListener  & setNotificationClickListener are not working when we integrated Pushy with Firebase Auth (Phone). 

Our App would like to use Pushy for notification and Firebase Auth(Phone) as the login solution, my environment is Flutter 1.22.4, below is the plugin version:

  pushy_flutter: ^1.1.6
  firebase_core: 0.5.2
  firebase_messaging: ^8.0.0-dev.8
  firebase_auth: 0.18.3

I disable the swizzling in the Info.plist	
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>

I also implemented the below logic in AppDelegate.swift
```
import UIKit
import Flutter
import Firebase
import FirebaseAuth
import UserNotifications
import FirebaseInstanceID

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
 override func application(
   _ application: UIApplication,
   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
 ) -> Bool {
       print("init")
       FirebaseApp.configure()
       GeneratedPluginRegistrant.register(with: self)
    if #available(iOS 10.0, *) {
               print("mark11")
             UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
   }
   application.registerForRemoteNotifications()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
 }

   override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
       let firebaseAuth = Auth.auth()
       firebaseAuth.setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
       return super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
   }

   override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

       let firebaseAuth = Auth.auth()
    if (firebaseAuth.canHandleNotification(userInfo)) {
        completionHandler(.noData)
        return
    }
      return super.application(application, didReceiveRemoteNotification: userInfo, fetchCompletionHandler: completionHandler)
   
   }
}
``` 

Flutter code:

```
import 'package:flutter/services.dart';
import 'dart:io' show Platform;

import 'package:flutter/services.dart';
import 'package:pushy_flutter/pushy_flutter.dart';

import '../../util/_base_export.dart';
import 'app_main.dart';
import '../others/page_upgrade.dart';
import '../others/page_select_wh.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

class AppFrameView extends StatefulWidget {
  @override
  _AppFrameViewState createState() => _AppFrameViewState();
}

class _AppFrameViewState extends State<AppFrameView> {
  String _deviceToken = 'Loading...';

  @override
  void initState() {
    super.initState();
    // print('Pushy starting');
    initPlatformState();
  }

  void backgroundNotificationListener(Map<String, dynamic> data) {
    // Print notification payload data
    print('Received notification: $data');
    // Notification title
    String notificationTitle = 'MyApp';
    // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
    String notificationText = data['message'] ?? 'Hello World!';
    // Android: Displays a system notification
    // iOS: Displays an alert dialog
    Pushy.notify(notificationTitle, notificationText, data);
    // Clear iOS app badge number
    Pushy.clearBadge();
  }

  Future<void> initPlatformState() async {
    Pushy.listen();
    // Start the Pushy service
    print('Pushy listened');
    // Set custom notification icon (Android)
    Pushy.setNotificationIcon('ic_notify');
    try {
      // Register the device for push notifications
      String deviceToken = await Pushy.register();

      // Print token to console/logcat
      print('Device token: $deviceToken');

    } on PlatformException catch (error) {
      // Print to console/logcat
      print('Error: ${error.message}');

    }

    // Listen for push notifications received
    Pushy.setNotificationListener(backgroundNotificationListener);

    // Listen for push notification clicked
    Pushy.setNotificationClickListener((Map<String, dynamic> data) {
      // Print notification payload data
      print('Notification clicked: $data');
      Pushy.clearBadge();
    });
  }

  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(
      context,
      designSize: Size(AppScreen.initWidth, AppScreen.initHeight),
      allowFontScaling: false,
    );
    return MaxScaleTextWidget(
      max: 1.0,
      child: Builder(
        builder: (context) {
          if (((AppSession.packageInfo?.version ?? '') != AppSession.appUtil.last_version) &&
              (AppSession.appUtil.force_update == true))
            return OtherUpgradePage();
          else if (AppSession.wh_id == 0)
            return SelectWhPage();
          else
            return AppMainView();
        },
      ),
    );
  }
}

```

The symptom is, 
1. I can fetch the device token,
2. Firebase Auth is working
3. Notification can be received.
4. However the backgroundNotificationListener  & setNotificationClickListener doesn't work, no matter inside App or outside App, and the badge won't be removed even if I navigated back to App

Then, I tried to modify the logic about the AppDelegate with below:
  
```
override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

       let firebaseAuth = Auth.auth()
    // if (firebaseAuth.canHandleNotification(userInfo)) {
    //    completionHandler(.noData)
    //    return
    // }
      return super.application(application, didReceiveRemoteNotification: userInfo, fetchCompletionHandler: completionHandler)
   
   }
```
After the rebuild, Pushy is totally working well, however, the Firebase Auth didn't work and shown below message:
"com.google.firebase.auth" : {
    "warning" : "This fake notification should be forwarded to Firebase Auth."
  }

I also tried to remove the "FirebaseAppDelegateProxyEnabled" setting in the Info.plist, but the Pushy can't fetch the device token.

That's issue I faced. Could you take a look and advise? Thanks so much.

Anthony

**Comment by chanmaoinc** [comment]
Hello @pushy-me , could you take a look and advise when you have free time? Thanks.

**Comment by anthonycmeow** [comment]
Hello @pushy-me , could you take a look and advise when you have free time? Thanks.

**Comment by pushy-me** [comment]
Hi @anthonycmeow,
Apologies for the late reply. 

Please try modifying your `didReceiveRemoteNotification` to the following:

```
override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

       let firebaseAuth = Auth.auth()
       firebaseAuth.canHandleNotification(userInfo);

      return super.application(application, didReceiveRemoteNotification: userInfo, fetchCompletionHandler: completionHandler)
   
   }
```

This might ensure that the notifications coming in are passed to both Firebase Auth & the Pushy iOS SDK.

**Comment by anthonycmeow** [comment]
Thanks @pushy-me , I tried this solution and Pushy is working. However, Firebase Auth didn't work in this case and I got the below output log for you reference. Any suggestion? Thanks,

```
flutter: Pushy notification received: {com.google.firebase.auth: {warning: This fake notification should be forwarded to Firebase Auth.}}
flutter: Received notification: {com.google.firebase.auth: {warning: This fake notification should be forwarded to Firebase Auth.}}
flutter: notification-not-forwarded
flutter: If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotificaton: method.
```

**Comment by pushy-me** [comment]
Hi @anthonycmeow,
Maybe try the following code instead, to invoke Pushy first (directly) & Firebase Auth later?

```
override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
     let pushy = Pushy(UIApplication.shared)
     pushy.application(application, didReceiveRemoteNotification userInfo:userInfo, completionHandler: completionHandler)

     let firebaseAuth = Auth.auth()
     if (firebaseAuth.canHandleNotification(userInfo)) {
        completionHandler(.noData)
        return
     }   
   }
```

Add the following `import` statement at the top:
```
import Pushy
```

Otherwise, this issue needs to be investigated with Firebase Support, as you have followed the docs correctly and are calling FIRAuth's `canHandleNotificaton` method as instructed in the log:

```
flutter: If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate 
need to be forwarded to FIRAuth's canHandleNotificaton: method.
```

**Comment by anthonycmeow** [comment]
Hi @pushy-me, 

I modified the code as below, the Firebase Auth is working well, at this time the Pushy backgroundNotificationListener is triggered also(I can see the popup from Pushy backgroundNotificationListener method). That's great!
```
  override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
     let pushy = Pushy(UIApplication.shared)
     pushy.application(application, didReceiveRemoteNotification: userInfo, fetchCompletionHandler: completionHandler)

     let firebaseAuth = Auth.auth()
     firebaseAuth.canHandleNotification(userInfo);
    
     return
   }   
```

However, there are still two problems: 
1. When App is opened, I sent a notification via Pushy API, no Pushy listener method would be called.
2. When outside the App,  I sent a notification via Pushy API, I can see the notification and the badge, but setNotificationClickListener didn't triggered when I clicked the notification, and the badge is still here even I opened the App.

Could you take a look also? Thanks so much!

Regards,
Anthony

**Comment by pushy-me** [comment]
Hi @anthonycmeow,
1) You mentioned above that the Pushy `backgroundNotificationListener` is triggered. But you also just mentioned the listener isn't called. When is it being called?
2) Notification click listener: Are you invoking `Pushy.listen()` in your `lib/main.dart` file's `initState()` method?

Note: If your main.dart does not yet have an initState(), simply define it under your State<> class, e.g. _MyHomePageState:
```
@override
void initState() {
    super.initState();
    
    // Start the Pushy service
    Pushy.listen();
}
```

**Comment by anthonycmeow** [comment]
@pushy-me  Sorry for the late reply.

For the first question, backgroundNotificationListener was triggered when I used Firebase Auth to send the verification code. However, the Listener wasn't triggered when I sent the notification via API. 
Below are two scenarios when I called the API to send the notification:
Nothing happened if the app was opened.
I received the notification when I closed the App. I opened the app, the badge will not be removed.

I also tried the approach you mentioned about the  " Pushy.listen();  " , the result is the same.
Let me know if there is any idea. Thanks so much.

**Comment by pushy-me** [comment]
Hi @anthonycmeow,
It may be that instantiating the Pushy object multiple times instead of using the existing instance is causing this issue.

Please try the following:

1. Install version `1.1.7` of our Flutter SDK by editing the `pubspec.yaml` in the root directory of your project and adding the following under the dependencies section:

```
pushy_flutter: 1.1.7
```

Run `flutter pub get` to fetch the dependency.

2. Replace your `didReceiveRemoteNotification` with the following:

```
  override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
     Pushy.shared?.application(application, didReceiveRemoteNotification: userInfo, fetchCompletionHandler: completionHandler)

     let firebaseAuth = Auth.auth()
     firebaseAuth.canHandleNotification(userInfo);
    
     return
   }   
```

Let us know if notifications are triggering the notification listener properly now.

**Comment by anthonycmeow** [comment]
@pushy-me  I have tried but didn't work.  iOS only.

**Comment by pushy-me** [comment]
Hi @anthonycmeow,
I apologize but we do not have anything further to suggest on how to resolve this issue. 

Unfortunately, this scenario of using Pushy & Firebase Auth at the same time is not currently supported.

**Comment by anthonycmeow** [comment]
Thanks @pushy-me, I totally understand, please close this issue for now and I will update if I got any solution in the future.
Thanks again.

**Comment by pushy-me** [comment]
Hi @anthonycmeow,
Please see this new development, which may help resolve your issue:
https://github.com/pushy-me/pushy-flutter/issues/20#issuecomment-738842642
