### ISSUE TITLE
Notification does not work when app is closed on Android emulator and device.

### ISSUE THREAD

**Issue by liqiang1995** [pushy-me/pushy-flutter#21]
How are you?
I am using pushy_flutter: ^1.1.8.
While the app is closed, Notification does not come to both Android emulator and device.
I tested pushy-flutter-demo. but it is not working for me.
When app is in background, notification is working well.
Is there a way to fix this issue?

**Comment by pushy-me** [comment]
Hi Super Coder,
Nice to connect with you. We'd be glad to help you investigate this issue
further.

If you could please provide the following information about a device
experiencing
this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by liqiang1995** [comment]
I don't think it is because of a device.

**Comment by liqiang1995** [comment]
Hi,
I found the issue.
My app is using flutter_rtmp_publisher: ^0.0.1.
If I removed the package, the notification works well even if the app is closed.

**Comment by pushy-me** [comment]
Hi @liqiang1995,
Yes, it is most likely that the `flutter_rtmp_publisher` is throwing an exception because it is trying to access `activity()` when the isolate is being started.

Please check if there is any exception thrown, when receiving a notification while your app is closed and the plugin installed?

Run `adb logcat` and post the exception here.

**Comment by pushy-me** [comment]
Hi @liqiang1995,
Indeed, the plugin `flutter_rtmp_publisher` was designed for foreground use only and  is trying to access `registrar.activity()` in `registerWith()` which is null when a Flutter background isolate is started.
https://github.com/ponnamkarthik/FlutterRtmpPlublisher/blob/8ae222dc6850fb2f01ad4716d59774c19ac37dc5/android/src/main/kotlin/io/github/ponnamkarthik/flutterrtmppublisher/FlutterRtmpPublisherPlugin.kt#L51

Please edit the outdated plugin to check for a null `registrar.activity()`, as mentioned here:
https://stackoverflow.com/a/58813854

**Comment by liqiang1995** [comment]
thank you.
Let me try so.
