### ISSUE TITLE
Triggering actions within the app with 1.1.x

### ISSUE THREAD

**Issue by calvinmuller-wi** [pushy-me/pushy-flutter#23]
We used to have code like this using 1.0.x which would allow us to dispatch actions view `redux` when a pushy was received, however with 1.1.x this needs to live outside of a widget so how would I go about getting the `context` when a pushy is received when the app is in the foreground.

```
Pushy.setNotificationListener((data) {
        RemoteNotifications.handleMessage(
          data,
          handler: "onMessage",
          store: store,
        );
      });
```
Thanks

**Comment by pushy-me** [comment]
Hi @calvinmuller-wi,
That's a great question, thanks for reaching out.

We recommend creating a top-level variable to hold a reference to your `State<>` class context, which can be accessed inside the `backgroundNotificationListener`, to pass notifications to your `Widget` context as follows:

1. Add a top-level variable, replacing `_PushyDemoState` with your own `State<>` class name:

```
_PushyDemoState currentState;
```

2. Add this code in the `void initState() {}` method of your `State` class implementation:

```
currentState = this;
```

3. Add a new method in your `State<>` class to process notifications in foreground:

```
  void onNewNotification(Map<String, dynamic> data) {
      // ....
  }
```

4. Access the state in `backgroundNotificationsListener` (will be null if it's running in the background) and invoke your method:

```
void backgroundNotificationListener(Map<String, dynamic> data) {
    // Print notification payload data
    print('Received notification: $data');


   // If app is in foreground, pass notification to Widget
   if (currentState != null) {
       currentState.onNewNotification(data);
   }

    // .......
}
```

Please let us know if you have any further questions or face any issues.
