### ISSUE TITLE
Feature request: expose the setting for notification icon colour on Android

### ISSUE THREAD

**Issue by yixiaoyx** [pushy-me/pushy-flutter#24]
I need to set the colour for the notification icon and I noticed it is not exposed in this package. Is it possible to add that in?

**Comment by pushy-me** [comment]
Hi @yixiaoyx,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Please consult this article for a solution:
https://support.pushy.me/hc/en-us/articles/360044212951-How-can-I-customize-the-Android-notification-on-Flutter-

Please let me know if there's anything else we can help with.
