### ISSUE TITLE
`Pushy.setNotificationListener` has no effect on iOS

### ISSUE THREAD

**Issue by yixiaoyx** [pushy-me/pushy-flutter#25]
It seems the `Pushy.setNotificationListener` method has no effect on iOS. The listener I passed into it is not called when the app runs on iOS. I need to display the notification based on fields in the `data` payload as well as user data in the app, however without being able to pass in a notification listener I am not able to do either. Based on your documentation and examples, this method is said to be available for both platforms. Could you please fix it? Thanks!

**Comment by pushy-me** [comment]
Hi @yixiaoyx,
Thanks for reaching out. We'd be glad to assist with your inquiry.

On iOS, the notification being displayed needs to be set on the server-side, by setting the relevant keys in the `notification` object of the [Send Notifications API](https://pushy.me/docs/api/send-notifications):

```
{
    "to": "a6345d0278adc55d3474f5",
    "data": {
        "message": "Hello World!"
    },
    "notification": {
        "body": "Hello World \u270c",
        "badge": 1,
        "sound": "ping.aiff"
    }
}
```

The `Pushy.setNotificationListener` callback will only be invoked when the app is opened by interacting with the notification (tap/swipe on it).

Please let me know if there's anything else we can help with.

**Comment by yixiaoyx** [comment]
@pushy-me Thanks for the reply. However I found that `Pushy.setNotificationListener` is not invoked even if I tap on the notification to open the app on iOS. Is this method in fact Android only? And does that mean there is no way I can access the `data` payload on iOS?

**Comment by pushy-me** [comment]
Hi @yixiaoyx,
Please make sure you initialized our plugin in `AppDelegate.m`.

Initialize the plugin by adding the following line to your `ios/app/AppDelegate.m` file, anywhere inside your app's `didFinishLaunchingWithOptions` method:

```
// Initialize Pushy Module
[PushyModule didFinishLaunchingWithOptions:launchOptions];
```

Make sure to add the required import statement:

```
#import <PushyModule.h>
```
Also, please ensure you are not using any other push plugins such as FCM or [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) (except the local notification functionality of that plugin).

**Comment by yixiaoyx** [comment]
@pushy-me Thanks, could you elaborate a bit on how does FCM plugin affect the notification on iOS? According to your other answer we need the FCM plugin for Android FCM fallback and our app needs to support both Android and iOS.

**Comment by yixiaoyx** [comment]
@pushy-me Also, your flutter plugin does not have a `didFinishLaunchingWithOptions` method on iOS. I already did pod install and the following is being called in the app's `didFinishLaunchingWithOptions` method:
 ```
[PushyPlugin registerWithRegistrar:[registry registrarForPlugin:@"PushyPlugin"]];
```

**Comment by pushy-me** [comment]
Hi @yixiaoyx,
Please ignore the previous suggestion to invoke `didFinishLaunchingWithOptions` as it only applies to the Pushy React Native SDK.

Instead, it seems the issue is directly related to the use of Firebase & Pushy together, which is causing a conflict because both SDKs use AppDelegate method swizzling. Please follow the steps mentioned here to resolve this conflict:
https://github.com/pushy-me/pushy-flutter/issues/20#issuecomment-738842642

Feel free to comment here if you face any further difficulties.

**Comment by yixiaoyx** [comment]
@pushy-me Thanks for the clarification. I followed the instructions to disable method swizzling and add in overriding methods, however the callback still isn't getting called on iOS. I put a breakpoint in AppDelegate.swift in the two overriding methods for `didReceiveRemoteNotification`, and found that they never got called when a notification is received and displayed. Also, although the latest version did fix toggling notification on Android, it has no effect on iOS.

**Comment by pushy-me** [comment]
@yixiaoyx Please make sure to also disable the Firebase SDK method swizzling as follows:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in
