### ISSUE TITLE
notification icon grey out

### ISSUE THREAD

**Issue by callmejm** [pushy-me/pushy-flutter#30]
I have set `Pushy.setNotificationIcon('ic_notification');` after `Pushy.listen();` and put all ic_notification.png to all mipmap folder , but the notification is still grey out.

**Comment by pushy-me** [comment]
Hi @callmejm.
We'd be glad to assist.

Is your icon showing up in greyscale, or simply a grey box? Please see this for a solution:
https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/

**Comment by pushy-me** [comment]
Hi @callmejm,
Basically, that's happening because your notification icon is **not transparent**.

Please read the article again as it explains this very clearly:
https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/

You must modify your notification icon to be fully transparent, with the visible logo in white pixels.

> The Android system ignores all non-alpha channels in action icons and in the main notification icon. You should assume that these icons will be alpha-only. The system draws notification icons in white and action icons in dark gray.

**Comment by callmejm** [comment]
how to show ios notification on foreground instead of alert? I have added
this code on AppDelegate.swift

if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as?
UNUserNotificationCenterDelegate
}

**Comment by callmejm** [comment]
@pushy-me the grey out issue still exist, I already follow the instructions to generate the icon, but the icon still grey box. I have put icon into all mipmap folder and named ic_notification

**Comment by pushy-me** [comment]
Hi @callmejm,
In Objective-C (Flutter iOS), please import Pushy as follows:

```
@import Pushy
```

Please let us know if it works.
