### ISSUE TITLE
Running on Release I got "No serializer found for class..."

### ISSUE THREAD

**Issue by thiagoloureiro** [pushy-me/pushy-flutter#32]
![image](https://user-images.githubusercontent.com/29433794/126137419-f6503c46-9be9-4d01-96bb-9655fa2371b4.png)

```
I/flutter ( 6534): Error: No serializer found for class c.a.a.e.c.a and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
Application finished.
```

Tried with my local app and the example app from here.

(in debug mode works normally)

Device - Pixel 5

**Comment by pushy-me** [comment]
Hi @thiagoloureiro,
Thanks for your report. Flutter comes preconfigured with ProGuard. Our [Flutter docs](https://pushy.me/docs/additional-platforms/flutter) mention the following instruction:

Please make sure the following lines are present in your `android/app/proguard-rules.pro` file (please create this file if it doesn't exist yet):

```
-dontwarn me.pushy.**
-keep class me.pushy.** { *; }
```

Please add these lines to your `proguard-rules.pro` file, and run the app again. The error should be resolved.
