### ISSUE TITLE
setNotificationClickListener not working in IOS

### ISSUE THREAD

**Issue by pkphone** [pushy-me/pushy-flutter#34]
I need to listen to the Push notification when a user clicking on it. So I used setNotificationClickListener to listen on user click, but unfortunately, I am not getting any response on it.

**Comment by pushy-me** [comment]
Hi @pkphone,
We'd be glad to assist.

1) Where are you invoking `setNotificationClickListener()`? Please ensure it is inside `initState()`, as implemented [here](https://github.com/pushy-me/pushy-demo-flutter/blob/master/lib/main.dart#L105). Also, please share your `lib/main.dart`, if possible.

2) Please clone and run our [Pushy Flutter Demo](https://github.com/pushy-me/pushy-demo-flutter) app and check whether the notification click listener is working there. This will rule out a device-related or Xcode-related issue.

**Comment by pkphone** [comment]
I put this setNotificationClickListener inside initState().

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  await Hive.initFlutter();
  registerAdapters();
  runApp(
    EasyLocalization(
      supportedLocales: [Locale('en'), Locale('mm'), Locale('mmu')],
      path: 'assets/translations',
      fallbackLocale: Locale('en'),
      child: ModularApp(
        module: AppModule(),
        child: AppWidget(),
      ),
    ),
  );
}

void backgroundNotificationListener(Map<String, dynamic> data) async {
  NotiStore notiStore = Modular.get<NotiStore>();

  if (Platform.isAndroid) {
    NotiMessage notiMessage = NotiMessage.fromJson(jsonDecode(data['__json']));
    await notiStore.saveToNotiMessage(notiMessage);
  } else if (Platform.isIOS) {
    NotiMessage notiMessage = NotiMessage();
    notiMessage.title = data['title'];
    notiMessage.message = data['message'];
    notiMessage.image = data['image'];
    notiMessage.requestId = data['request_id'];
    notiMessage.requestType = data['request_type'];
    notiMessage.slug = data['slug'];
    await notiStore.saveToNotiMessage(notiMessage);
  }

  String notificationTitle = Strings.appName;

  String notificationText = data['message'] ?? '';

  Pushy.notify(notificationTitle, notificationText, data);

  Pushy.clearBadge();
}

**Comment by pushy-me** [comment]
Hi @pkphone,
At this time, `Pushy.setNotificationListener()` and `Pushy.setNotificationClickListener()` must be executed directly from within your `lib/main.dart`, and no sub-widget files.

Please move this method to `lib/main.dart`'s `initState()` method, and give it another try.

**Comment by pushy-me** [comment]
Closing due to lack of response, please feel free to comment if you still need help with this issue.
