### ISSUE TITLE
Upgrade sdk version (1.0.77 -> 1.0.79)

### ISSUE THREAD

**Issue by bubupro9x** [pushy-me/pushy-flutter#39]
Hi,
Currently, pushy Android SDK has a new version (1.0.79). Can you upgrade?

**Comment by bubupro9x** [comment]
https://pushy.me/docs/android/sdk-changelog

**Comment by pushy-me** [comment]
Hi @bubupro9x,
We'd be glad to assist.

The Pushy Flutter SDK was already updated to reference Pushy Android SDK `1.0.79` in version `2.0.4` published to `npm`.

Please install version `2.0.4` of our [Flutter SDK](https://pub.dev/packages/pushy_flutter) by editing the `pubspec.yaml` in the root directory of your project and updating the `pushy_flutter` dependency version:

```
pushy_flutter: 2.0.4
```

Then, run `flutter pub get` to fetch the new version.
