### ISSUE TITLE
[ iOS ] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"

### ISSUE THREAD

**Issue by pyae-sone-phyo** [pushy-me/pushy-flutter#4]
Hi ! I face this issue in pushy flutter while build for iOS 

This is the logs 
> [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x282836040, domain=1, instance=1>

Thanks for any help.

**Comment by pushy-me** [comment]
Hi @pyae-sone-phyo,
This can happen if you forgot to enable the `Push Notifications` capability in your Xcode project as mentioned in the [Pushy Flutter SDK integration docs](https://pushy.me/docs/additional-platforms/flutter). 

![Screen Shot 2019-12-27 at 1 55 03 PM](https://user-images.githubusercontent.com/13287630/71495027-7fb2c980-28b0-11ea-840a-c82530679762.png)

**Comment by pushy-me** [comment]
Hi @pyae-sone-phyo,
I see you have edited the issue with a different error message than before.

For `NSPOSIXErrorDomain  Code=13` please refer to the following:
https://stackoverflow.com/questions/53526194/how-to-troubleshoot-resolve-signal-strength-query-returned-error-logs-that-are
