### ISSUE TITLE
Unable to turn off notifications using Pushy.toggleNotifications(false), Even with Pushy.toggleFCM(false)

### ISSUE THREAD

**Issue by cabonitavince** [pushy-me/pushy-flutter#41]
Pushy.toggleNotifications(false);
Pushy.toggleFCM(false);

No logs displayed too.
Pushy version: ^2.0.5

**Comment by pushy-me** [comment]
Hi @cabonitavince,
Thanks for reporting this issue. We'd be glad to assist.

Calling `Pushy.toggleNotifications(false)` should definitely prevent new notifications from coming through on Android devices. Are you experiencing the issue on an Android or iOS device? Please be advised that this method is currently only supported on Android.

The best way to understand what is happening behind the scenes is to inspect the Android device logcat, specifically, the Pushy SDK logs. If you could please follow these instructions to export the device logcat from one of the affected devices after calling `Pushy.toggleNotifications(false)`, that would be greatly appreciated:

1. Install "adb" by following the instructions in [this guide](http://lifehacker.com/the-easiest-way-to-install-androids-adb-and-fastboot-to-1586992378)

2. Enable [Developer Options](http://www.greenbot.com/article/2457986/how-to-enable-developer-options-on-your-android-phone-or-tablet.html) in the device settings

3. Connect the device to your computer via a USB cable

4. If the "Trust this computer" dialog appears on the device, press "Yes"

5. Open a terminal prompt on your computer

6. Run adb logcat -d *:S Pushy > logcat.txt

7. Attach logcat.txt to this issue, or send it to us privately via e-mail at support@pushy.me

Thanks for your assistance in helping us investigate and resolve this issue!

**Comment by pushy-me** [comment]
Closing the issue due to lack of response, feel free to reply if you still need help with this.
