### ISSUE TITLE
pushy-flutter causes crash during hot reload

### ISSUE THREAD

**Issue by da-revo** [pushy-me/pushy-flutter#7]
`
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): Failed to handle method call
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at me.pushy.sdk.util.PushyPersistence.getEnvironmentExternalStoragePath(PushyPersistence.java:28)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at me.pushy.sdk.util.PushyAuthentication.getDeviceCredentials(PushyAuthentication.java:27)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at me.pushy.sdk.util.PushyServiceManager.start(PushyServiceManager.java:22)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at me.pushy.sdk.Pushy.listen(Pushy.java:33)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at me.pushy.sdk.flutter.PushyPlugin.onMethodCall(PushyPlugin.java:113)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#me.pushy.sdk.flutter/methods(25615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/Pushy   (25615): Flutter app is listening for notifications
E/EventChannel#me.pushy.sdk.flutter/events(25615): Failed to open event stream
E/EventChannel#me.pushy.sdk.flutter/events(25615): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at me.pushy.sdk.flutter.PushyPlugin.onListen(PushyPlugin.java:196)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at android.os.Looper.loop(Looper.java:174)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/EventChannel#me.pushy.sdk.flutter/events(25615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/Pushy   (25615): Failed to request WRITE_EXTERNAL_STORAGE permission
D/Pushy   (25615): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
D/Pushy   (25615): 	at me.pushy.sdk.flutter.PushyPlugin.requestStoragePermission(PushyPlugin.java:301)
D/Pushy   (25615): 	at me.pushy.sdk.flutter.PushyPlugin.onMethodCall(PushyPlugin.java:126)
D/Pushy   (25615): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
D/Pushy   (25615): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
D/Pushy   (25615): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
D/Pushy   (25615): 	at android.os.MessageQueue.nativePollOnce(Native Method)
D/Pushy   (25615): 	at android.os.MessageQueue.next(MessageQueue.java:336)
D/Pushy   (25615): 	at android.os.Looper.loop(Looper.java:174)
D/Pushy   (25615): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
D/Pushy   (25615): 	at java.lang.reflect.Method.invoke(Native Method)
D/Pushy   (25615): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
D/Pushy   (25615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(25615): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(25615): Process: com.example.go_pl_hd, PID: 25615
E/AndroidRuntime(25615): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkCallingOrSelfPermission(java.lang.String)' on a null object reference
E/AndroidRuntime(25615): 	at me.pushy.sdk.util.PushyPermissionVerification.verifyManifestPermissions(PushyPermissionVerification.java:26)
E/AndroidRuntime(25615): 	at me.pushy.sdk.Pushy.register(Pushy.java:219)
E/AndroidRuntime(25615): 	at me.pushy.sdk.flutter.PushyPlugin$1.run(PushyPlugin.java:172)
E/AndroidRuntime(25615): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(25615): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(25615): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(25615): 	at java.lang.Thread.run(Thread.java:919)
I/Process (25615): Sending signal. PID: 25615 SIG: 9
Application finished.
`

**Comment by pushy-me** [comment]
Hi @da-revo,
Thanks for the report. We've attempted a fix in https://github.com/pushy-me/pushy-flutter/commit/61ce9656cc50216199a4058d1005c8c133edd4b1 and published to pub.dev as `1.0.10`. 

Please update the [Pushy Flutter SDK](https://pushy.me/docs/additional-platforms/flutter) in your app by editing the `pubspec.yaml` in the root directory of your project and updating the `pushy_flutter` package version to `1.0.10`:
```
pushy_flutter: 1.0.10
```

Then, run `flutter pub get` to fetch the new package.

---

Run your app and let us know if the issue is fixed!

**Comment by da-revo** [comment]
Thanks a lot for the really quick fix  :)

It no longer crashes.

Here is what is shown in the output now,
`

W/Pushy   (25292): Flutter app is listening for notifications
D/Pushy   (25292): Failed to request WRITE_EXTERNAL_STORAGE permission
D/Pushy   (25292): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
D/Pushy   (25292): 	at me.pushy.sdk.flutter.PushyPlugin.requestStoragePermission(PushyPlugin.java:304)
D/Pushy   (25292): 	at me.pushy.sdk.flutter.PushyPlugin.onMethodCall(PushyPlugin.java:126)
D/Pushy   (25292): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
D/Pushy   (25292): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
D/Pushy   (25292): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
D/Pushy   (25292): 	at android.os.MessageQueue.nativePollOnce(Native Method)
D/Pushy   (25292): 	at android.os.MessageQueue.next(MessageQueue.java:336)
D/Pushy   (25292): 	at android.os.Looper.loop(Looper.java:174)
D/Pushy   (25292): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
D/Pushy   (25292): 	at java.lang.reflect.Method.invoke(Native Method)
D/Pushy   (25292): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
D/Pushy   (25292): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Reloaded 5 of 881 libraries in 941ms.
`

I have added `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    ` already and given permission on device

**Comment by pushy-me** [comment]
Hi @da-revo,
Where are you invoking `Pushy.requestStoragePermission()`?

Please try moving its invocation to `initState()` in your `lib/main.dart` file:

```
@override
void initState() {
    super.initState();
    
    // Start the Pushy service
    Pushy.listen();

    // Request the WRITE_EXTERNAL_STORAGE permission on Android so that the Pushy SDK will be able to persist the device token in the external storage
    Pushy.requestStoragePermission();
}
```
