### ISSUE TITLE
Allow changing the alert tone

### ISSUE THREAD

**Issue by calvinmuller-wi** [pushy-me/pushy-flutter#8]
The code at https://github.com/pushy-me/pushy-flutter/blob/68f368c2488e0b1af5c6f9f4d62da1e22f7c9d1a/android/src/main/java/me/pushy/sdk/flutter/PushReceiver.java#L35 seems to set the default sound and you're unable to change/disable it.

Is it possible to make it configurable? or is there any solution to try and disable the sound?

Thanks

**Comment by pushy-me** [comment]
Hi @calvinmuller-wi,
I'd be glad to assist with your inquiry.

You can modify the default push `BroadcastReceiver` implementation to customize or remove the sound altogether.

Create a file `PushReceiver.java` in the following path:
```
android/app/src/main/java/PushReceiver.java
```

Paste the contents of the [default PushReceiver.java](https://raw.githubusercontent.com/pushy-me/pushy-flutter/master/android/src/main/java/me/pushy/sdk/flutter/PushReceiver.java) into this file.

**Note:** You will need to update the package declaration to reflect your app's package name.

When you are done modifying the default implementation, edit your `android/app/src/main/AndroidManifest.xml`, replacing `me.pushy.sdk.flutter.PushReceiver` with `.PushReceiver` in the following declaration:

```
<!-- Pushy Notification Receiver -->
<!-- Incoming push notifications will invoke the following BroadcastReceiver -->
<receiver android:name="me.pushy.sdk.flutter.PushReceiver" android:exported="false">
    <intent-filter>
        <!-- Do not modify this -->
        <action android:name="pushy.me" />
    </intent-filter>
</receiver>
```

Please let me know if you face any difficulties.
