### ISSUE TITLE
Unable to run on iOS

### ISSUE THREAD

**Issue by calvinmuller-wi** [pushy-me/pushy-flutter#9]
Getting the following error.
```
/Users/xxx/.pub-cache/hosted/pub.dartlang.org/pushy_flutter-1.0.11/ios/Classes/PushyPlugin.m:2:9: 'pushy_flutter/pushy_flutter-Swift.h' file not found
```

```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.20, on Mac OS X 10.15.1 19B88, locale en-ZA)
    • Flutter version 1.19.0-4.0.pre.20 at /Users/calvinmuller/iStreet/Mobile/flutter
    • Framework revision 2ece1c3a17 (33 hours ago), 2020-06-02 19:00:12 -0700
    • Engine revision 6589dcb2d4
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 3d53df52af)

```

**Comment by calvinmuller-wi** [comment]
added `  use_frameworks!` seemed to solve this issue.

**Comment by pushy-me** [comment]
HI @calvinmuller-wi,
Thanks for reaching out.

It appears that all new Flutter projects come preconfigured with `use_frameworks!` in the `ios/Podfile`.

If you specifically removed this line, it may indeed explain the error you encountered.

We've just verified with `flutter create testapp` that this is indeed the case.
